title: thiago prado - things of software
baseurl: ""
url: "https://tprado.github.io"

author: Thiago Prado
email: thiago.gozzi.prado@gmail.com
gpg_key_id: "0x04291DE1991F050D"
github_username: tprado

# Build settings
markdown: kramdown
timezone: America/Sao_Paulo
exclude: [README.md, Gemfile, Gemfile.lock, Makefile]
