title: Software Craftsman
email: thiago.gozzi.prado@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: ""
url: "http://tprado.github.io"
twitter_username: 5k1pp3r
github_username:  tprado

# Build settings
markdown: kramdown
timezone: America/Sao_Paulo
exclude: [README.md, Gemfile, Gemfile.lock]
